import { DemoPalette, Page, PushButton } from "common.slint";

export struct Category {
    category_id: string,
    category_name: string,
    parent_id: int,
}

export component CategoriesView inherits Page {
    // header: "Categories";
    // has-back-button: true;

    in-out property <[Category]> categories: [];
    callback on_category_selected(Category);

    Flickable {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 8; // Display of categories starts after Header

        VerticalLayout {
            spacing: 16px;
            for category in root.categories: PushButton {
                text: category.category_name;
                primary: true;
                clicked => { root.on_category_selected(category); }
            }
        }
    }
}
