import { DemoPalette, Page, PushButton } from "common.slint";

export component CategoriesView inherits Page {
    // header: "Categories";
    // has-back-button: true;

    in-out property <[string]> categories;
    callback on_category_selected(string);

    Flickable {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 2;

        VerticalLayout {
            spacing: 16px;
            for category in root.categories: PushButton {
                text: category;
                primary: false;
                clicked => { root.on_category_selected(category); }
            }
        }
    }
}
