import { DemoPalette, Page, PushButton } from "common.slint";

export struct Category {
    category_id: string,
    category_name: string,
    parent_id: int,
}

export struct LiveStream {
    num: int,
    name: string,
    stream_type: string,
    stream_id: int,
    stream_icon: string,
    epg_channel_id: string,
    added: string,
    is_adult: string,
    category_id: string,
    custom_sid: string,
    tv_archive: int,
    direct_source: string,
    tv_archive_duration: int,
}

enum SubPage { Categories, Streams }

export component LiveStreamView inherits Page {
    has-back-button: true;

    in-out property <string> category_name: "Streams"; // Default header
    in-out property <SubPage> current-subpage: SubPage.Streams;
    in-out property <Category> selected_category;

    in-out property <[LiveStream]> livestreams: [];
    callback on_livestream_selected(LiveStream);
    header: category_name;
    // TODO: Streams view is not scrollable here 
    Flickable {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 8;
        VerticalLayout {
            spacing: 16px;
            for live in root.livestreams: PushButton {
                text: live.name;
                primary: true;
                clicked => {
                    root.current-subpage = SubPage.Streams;
                    root.on_livestream_selected(live);
                }
            }
        }
    }

    // back => {
    //     root.current-subpage = SubPage.Categories;
    // }
}

export component LiveCategoriesView inherits Page {
    // header: "Categories";
    // has-back-button: true;

    in-out property <[Category]> categories: [];
    in-out property <[LiveStream]> livestreams: [];
    in-out property <SubPage> current-subpage: SubPage.Categories;
    in-out property <Category> selected_category;

    callback on_category_selected(Category);

    Flickable {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 8; // Display of categories starts after Header

        VerticalLayout {
            spacing: 16px;
            for category in root.categories: PushButton {
                text: category.category_name;
                primary: true;
                clicked => {
                    root.current-subpage = SubPage.Streams;
                    root.on_category_selected(category);
                }
            }
        }
        
        LiveStreamView {
            category_name: root.selected_category.category-name;
            livestreams : root.livestreams;
            back => { root.current-subpage = SubPage.Categories; }
            x: root.current-subpage == SubPage.Streams ? 0 : parent.width + parent.x + 2px;
            animate x { duration: 125ms; easing: ease; }
        }
    }
}
