import { DemoPalette, Page, PushButton } from "common.slint";
import { Spinner, ScrollView } from "std-widgets.slint";
export struct Category {
    category_id: string,
    category_name: string,
    parent_id: int,
}

export struct LiveStream {
    num: int,
    name: string,
    stream_type: string,
    stream_id: int,
    stream_icon: image,
    epg_channel_id: string,
    added: string,
    is_adult: string,
    category_id: string,
    custom_sid: string,
    tv_archive: int,
    direct_source: string,
    tv_archive_duration: int,
}

enum SubPage { Categories, Streams }

component ActionButton inherits Rectangle {
    in property <image> icon <=> img.source;
    in property <string> text <=> label.text;
    in property <int> stream_id: 10;
    in property <LiveStream> stream_data;

    width: DemoPalette.button-width;
    height: DemoPalette.button-height;

    callback clicked(int);

    VerticalLayout {
        spacing: 10px;

        Rectangle {
            border-radius: 25px;
            border-width: 5px;
            // border-color: DemoPalette.secondary;
            border-color: white;
            background: DemoPalette.dark-mode ? DemoPalette.primary : DemoPalette.background;
            width: DemoPalette.button-width;
            height: self.width;

            img := Image {
                width: 130px;
                height: 130px;
                image-fit: contain;
                // Without this condition, application will crash as the default image has height,width of 0
                visible: root.icon.height != 0;
            }

            Spinner {
                progress: 50%;
                indeterminate: true;
                visible: root.icon.height == 0; // Show only if icon is empty
            }
        }

        label := Text {
            font-size: DemoPalette.base-font-size;
            font-weight: 800;
            horizontal-alignment: center;
            color: DemoPalette.text-primary;
            wrap: word-wrap;
        }
    }

    TouchArea {
        clicked => {
            root.clicked(root.stream_id)
        }
    }
}

export component LiveStreamView inherits Page {
    has-back-button: true;

    in-out property <string> category_name: "Streams"; // Default header
    in-out property <SubPage> current-subpage: SubPage.Streams;
    in-out property <Category> selected_category;
    in-out property <length> button-spacing: 35px;

    in-out property <[LiveStream]> livestreams: [];
    in-out property <LiveStream> livestream;
    in-out property <int> stream_id;
    callback on_livestream_selected(int);
    header: category_name;

    property <int> columns: floor(root.width / (DemoPalette.button-width + root.button-spacing));

    ScrollView {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 8;
        viewport-height: ceil(root.livestreams.length / root.columns) * (DemoPalette.button-height + root.button-spacing); // Dynamic height based on content 

        Rectangle {
            for live[idx] in root.livestreams: ActionButton {
                x: mod(idx, root.columns) * (DemoPalette.button-width + root.button-spacing);
                y: floor(idx / root.columns) * (self.height + root.button-spacing);
                text: live.name;
                icon: live.stream_icon;
                stream_id: live.stream_id;
                stream_data: live;
                clicked => {
                    // root.current-subpage = SubPage.Streams;
                    root.stream_id = self.stream_id; // Update stream_id
                    root.on_livestream_selected(self.stream_id);
                }
            }
        }
    }
}

export component LiveCategoriesView inherits Page {
    // header: "Categories";
    // has-back-button: true;

    in-out property <[Category]> categories: [];
    in-out property <[LiveStream]> livestreams: [];
    in-out property <LiveStream> livestream;
    in-out property <int> stream_id;
    in-out property <SubPage> current-subpage: SubPage.Categories;
    in-out property <Category> selected_category;

    callback on_category_selected(Category);
    callback on_livestream_selected(int);

    Flickable {
        width: parent.width;
        height: parent.height - DemoPalette.base-font-size * 8; // Display of categories starts after Header

        VerticalLayout {
            spacing: 16px;
            for category in root.categories: PushButton {
                text: category.category_name;
                primary: true;
                clicked => {
                    root.current-subpage = SubPage.Streams;
                    root.on_category_selected(category);
                }
            }
        }
    }

    LiveStreamView {
        category_name: root.selected_category.category-name;
        livestreams: root.livestreams;
        stream_id <=> root.stream_id;

        back => {
            root.current-subpage = SubPage.Categories;
        }
        x: root.current-subpage == SubPage.Streams ? 0 : parent.width + parent.x + 2px;
        animate x {
            duration: 125ms;
            easing: ease;
        }
        on_livestream_selected => {
            root.stream_id = stream_id;
            root.on_livestream_selected(stream_id);
        }
    }
}
