// login_view.slint
import { VerticalBox, HorizontalBox, LineEdit, Button } from "std-widgets.slint";

export component LoginView inherits Window {
    always-on-top: false;
    height: 600px;
    width: 800px;
    Image {source: @image-url("../assets/background.jpg");
image-fit: cover;}

    in-out property <string> url: "";
    in-out property <string> username: "";
    in-out property <string> password: "";
    callback login();

    VerticalBox {
        
        LineEdit {
            placeholder-text: "Enter URL";
            text <=> url;
            height: 90px;
        }

        LineEdit {
            placeholder-text: "Enter Username";
            text <=> username;
            height: 90px;
        }

        LineEdit {
            placeholder-text: "Enter Password";
            input-type: InputType.password;
            text <=> password;
            height: 90px;
        }

        HorizontalBox {
            // Center horizontally
            alignment: LayoutAlignment.center;
        Button {
                text: "Login";
                clicked => {
                    login();
                }
                height: 100px;
                width: 150px;
            }
        }
    }
}
