import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { DemoPalette, Page } from "common.slint";
import { SettingsPage } from "./settings.slint";
import { LiveCategoriesView, LiveStreamView, Category, LiveStream } from "./live_view.slint";
import { MoviesCategoriesView, MoviesView, Category, Movie } from "./movies_view.slint";

import "../assets/Amiri-Regular.ttf";
import { LoginView } from "login_view.slint";

component SideBarIcon inherits Rectangle {
    in-out property <bool> active;
    in-out property <image> icon <=> i.source;

    callback activate;
    width: DemoPalette.side-bar-width;
    height: 72px;

    Rectangle {
        x: DemoPalette.side-bar-margin;
        GridLayout {
            padding: 0px;
            @children
        }

        i := Image {
            colorize: root.active ? DemoPalette.active-page-icon-color : DemoPalette.inactive-page-icon-color;
            animate colorize { duration: 125ms; }
            width: 30px;
            height: 30px;
        }
    }

    TouchArea {
        clicked => {
            root.activate();
        }
    }
}

export component MainView inherits Window {
    in-out property <int> active-page: 6;
    in-out property <bool> sidebar-enabled: false; // Add this line

    in-out property <string> url: "";
    in-out property <string> username: "";
    in-out property <string> password: "";

    callback quit();

    min-width: 800px;
    min-height: 600px;
    title: "Xtream";
    background: DemoPalette.primary;
    default-font-family: "Amiri";
    default-font-size: DemoPalette.base-font-size;

    callback fetch-data();
    callback login(string, string, string); // Forward login callback to login_view
    callback handle_category_selected(int, Category);
    callback handle_livestream_selected(int);
    callback handle_movie_selected(int, string);


    in-out property <[Category]> live_tv_categories: [];
    in-out property <[Category]> movies_categories: [];
    in-out property <[Category]> series_categories: [];

    in-out property <[LiveStream]> livestreams: [];
    in-out property <LiveStream> livestream;

    in-out property <[Movie]> movies_streams: [];
    in-out property <Movie> movie;

    in-out property <int> stream_id;
    in-out property <string> extension;
    in-out property <Category> selected_category;

    HorizontalLayout {
        padding: 10px;
        padding-left: 67px;

        main-view := Rectangle {
            height: 100%;
            border-radius: 30px;
            background: DemoPalette.background;
            Rectangle {
                clip: true;
                x: main-view.border-radius / 2;
                y: main-view.border-radius / 2;
                width: main-view.width - main-view.border-radius;
                height: main-view.height - main-view.border-radius;

                function calcPageY(pageNumber: int) -> length {
                    if (root.active-page == pageNumber) {
                        return 0;
                    }
                    return root.active-page < pageNumber ? - self.height / 2 : parent.height / 2;
                }

                property <duration> page-animation-duration: 250ms;

                home-page := LiveCategoriesView {
                    header: "Live TV";
                    property <int> pageNumber: 0;
                    y: calcPageY(0);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }

                    categories <=> root.live_tv_categories;
                    livestreams <=> root.livestreams;
                    stream_id <=> root.stream_id; // Bind stream_id
                    selected_category <=> root.selected_category;

                    on_category_selected(category) => {
                        // Handle category selection for Live TV
                        root.handle_category_selected(0, category);
                        // root.current-subpage = SubPage.Streams;
                        // root.selected_category = category;
                    }
                    
                    on_livestream_selected(stream_id) => {
                        root.stream_id = stream_id; // Update stream_id
                        root.handle_livestream_selected(stream_id);
                    }

                }

                movies := MoviesCategoriesView {
                    header: "Movies - افلام";
                    property <int> pageNumber: 1;
                    y: calcPageY(1);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }

                    categories <=> root.movies_categories;
                    selected_category <=> root.selected_category;
                    movies_streams <=> root.movies_streams;
                    movie <=> root.movie;
                    stream_id <=> root.stream_id;
                    extension <=> root.extension;

                    on_category_selected(category) => {
                    // Handle category selection for Movies
                    root.handle_category_selected(1, category);
                    }

                    on_movie_selected => {
                        root.stream_id = stream_id; // Update stream_id
                        root.extension = extension;
                        root.handle_movie_selected(stream_id, extension);
                    }
                }

                // series := CategoriesView {
                //     header: "Series - مسلسلات";
                //     property <int> pageNumber: 2;
                //     y: calcPageY(pageNumber);
                //     opacity: root.active-page == pageNumber ? 1 : 0;
                //     animate y {
                //         duration: page-animation-duration;
                //         easing: ease-out-quad;
                //     }
                //     animate opacity {
                //         duration: page-animation-duration;
                //         easing: ease-out-quad;
                //     }
                //     categories <=> root.series_categories;
                //     on_category_selected(category) => {
                //     // Handle category selection for Series
                //     root.handle_category_selected(2, category);
                //     }
                // }

                Page {
                    header: "Favorites";
                    // page number is matching the y index in the position for the icon
                    property <int> pageNumber: 4;
                    y: calcPageY(pageNumber);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                }

                Page {
                    header: "Search";
                    // page number is matching the y index in the position for the icon
                    property <int> pageNumber: 5;
                    y: calcPageY(pageNumber);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                }

                Page {
                    header: "Update Content";
                    // page number is matching the y index in the position for the icon
                    property <int> pageNumber: 7;
                    y: calcPageY(pageNumber);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                }

                SettingsPage {
                    // page number is matching the y index in the position for the icon
                    property <int> pageNumber: 8;
                    y: calcPageY(pageNumber);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                }

                LoginView {
                    // page number is matching the y index in the position for the icon
                    property <int> pageNumber: 9;
                    y: calcPageY(pageNumber);
                    opacity: root.active-page == pageNumber ? 1 : 0;
                    animate y {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }
                    animate opacity {
                        duration: page-animation-duration;
                        easing: ease-out-quad;
                    }

                    // Bind the properties to the MainView's properties
                    url <=> root.url;
                    username <=> root.username;
                    password <=> root.password;

                    // Forward the login event to MainView with the data
                    login(url, username, password) => {
                        root.login(url, username, password);
                    }
                }
            }
        }
    }

    sidebar := Rectangle {
        function icon-y(index: int) -> length {
            debug("Index: ", index);
            return 100px // top padding
                + index * 72px;
        }
        x: 0px;
        width: DemoPalette.side-bar-width;

        Image {
            x: parent.width - self.width + 1px; // workaround pixel gap
            y: sidebar.icon-y(root.active-page) - self.width / 2;
            source: @image-url("../assets/page_selection.svg");
            colorize: DemoPalette.background;
            animate y { duration: 125ms; }
        }

        VerticalLayout {
            y: 82px;

            for page-icon[idx] in [
                @image-url("../assets/tv-icon.svg"),
                @image-url("../assets/movies-icon.svg"),
                @image-url("../assets/series-icon.svg"),
            ]: SideBarIcon {
                activate => {
                    if root.sidebar-enabled {
                        root.active-page = idx;
                    }
                }
                icon: page-icon;
                active: root.active-page == idx;
            }
        }

        Rectangle {
            y: sidebar.icon-y(3) + 17px;
            x: DemoPalette.side-bar-margin + 8px;
            background: DemoPalette.background;
            height: 2px;
            width: 37px;
        }

        SideBarIcon {
            activate => {
                if root.sidebar-enabled {
                    root.active-page = 4;
                }
            }

            y: sidebar.icon-y(4);
            x: 16px;
            height: 35px;
            width: 30px;
            icon: @image-url("../assets/favorite-icon.svg");
            active: root.active-page == 4;
        }

        SideBarIcon {
            activate => {
                if root.sidebar-enabled {
                    root.active-page = 5;
                }
            }

            y: sidebar.icon-y(5);
            x: 16px;
            height: 35px;
            width: 30px;
            icon: @image-url("../assets/search-icon.svg");
            active: root.active-page == 5;
        }

        Rectangle {
            y: sidebar.icon-y(6) + 17px;
            x: DemoPalette.side-bar-margin + 8px;
            background: DemoPalette.background;
            height: 2px;
            width: 37px;
        }

        SideBarIcon {
            activate => {
                if root.sidebar-enabled {
                    root.active-page = 7;
                }
            }

            y: sidebar.icon-y(7);
            x: 16px;
            height: 35px;
            width: 30px;
            icon: @image-url("../assets/update-icon.svg");
            active: root.active-page == 7;
        }

        SideBarIcon {
            activate => {
                if root.sidebar-enabled {
                    root.active-page = 8;
                }
            }

            y: sidebar.icon-y(8);
            x: 16px;
            height: 35px;
            width: 30px;
            icon: @image-url("../assets/settings.svg");
            active: root.active-page == 8;
        }

        SideBarIcon {
            activate => {
                root.active-page = 9;
            }

            y: sidebar.icon-y(9);
            x: 16px;
            height: 35px;
            width: 30px;
            icon: @image-url("../assets/login-icon.svg");
            active: root.active-page == 9;
        }
    }
}
