import { Button, ScrollView, ProgressIndicator} from "std-widgets.slint";
import { DemoPalette, Page, PushButton } from "common.slint";
// Define the MainContent component
enum SubPage { Categories, Streams, MovieSite }

component MainContent inherits Rectangle {
    in property <image> img-background <=> img-background.source;
    in property <image> img-poster <=> img-poster.source;
    in property <string> extension;
    in property <int> stream_id;

    // Properties for download state
    in-out property <bool> is_downloading: false;
    in-out property <bool> is_downloaded: false;

    // Properties for icons
    in-out property <image> download_icon: @image-url("../assets/download-icon.svg");
    in-out property <image> offline_icon: @image-url("../assets/downloaded.svg");

    // Property for progress
    in-out property <float> download_progress: 0.0;

    callback on_movie_selected(int, string);
    callback on_movie_download(int, string);

    padding: 20px;
    background: transparent;
    img-background := Image {
        width: parent.width;
        height: parent.height;
        image-fit: fill;
    }

    HorizontalLayout {
        spacing: 20px;
        // Left Side: Movie Poster and Play Button
        VerticalLayout {
            padding: 100px;
            spacing: 10px;

            // Movie Poster
            Rectangle {
                width: 250px;
                height: 370px;
                background: #6284FF;

                img-poster := Image {
                    width: 250px;
                    y: 0px;
                    height: 320px;
                    image-fit: fill;
                }

                // Play Button
                Image {
                    width: 50px;
                    height: 50px;
                    y: 320px;
                    source: @image-url("../assets/play-icon.svg");
                    colorize: white;
                    TouchArea {
                        clicked => {
                            // debug("Calling on_movie_selected from MainComponent");
                            root.on_movie_selected(root.stream_id, root.extension);
                        }
                    }
                }
            }
        }

        // Right Side: Movie Info and Buttons
        VerticalLayout {
            spacing: 10px;
            // Favorite and Download Buttons
            HorizontalLayout {
                spacing: 10px;

                Image {
                    width: 50px;
                    height: 50px;
                    source: @image-url("../assets/favorite-icon.svg");
                    colorize: white;
                    y: 200px;
                }

                Image {
                    width: 50px;
                    height: 50px;
                    source: {
                        if root.is_downloaded {
                            root.offline_icon
                        } else {
                            root.download_icon
                        }
                    };
                    colorize: white;
                    y: 200px;
                    visible: !root.is_downloading;
                    TouchArea {
                        clicked => {
                            // debug("Calling on_movie_selected from MainComponent");
                            root.on_movie_download(root.stream_id, root.extension);
                        }
                    }
                }

                // Progress Bar (visible only when downloading)
            ProgressIndicator {
                    width: 50px;
                    height: 50px;
                    y:200px;
                    visible: root.is_downloading;
                    progress: root.download_progress;
                }
            }

            // Movie Info
            // Text {
            //     text: "Release Date: 2008-06-06";
            //     font-size: 16px;
            //     color: black;
            //     height: 16px;
            // }

            // Text {
            //     text: "Runtime: 92 minutes";
            //     font-size: 16px;
            //     color: black;
            //     height: 16px;
            // }

            // Text {
            //     text: "Genre: Animation, Action, Adventure";
            //     font-size: 16px;
            //     color: black;
            //     height: 16px;
            // }

            // Text {
            //     text: "Rating: 7.2/10";
            //     font-size: 16px;
            //     color: black;
            //     height: 16px;
            // }
        }
    }
}

// Define the CastSection component
component CastSection inherits Rectangle {
    padding: 20px;

    VerticalLayout {
        spacing: 10px;

        Text {
            text: "Cast";
            font-size: 20px;
        }

        ScrollView {
            HorizontalLayout {
                spacing: 10px;

            // Example Cast Member [To be filled dynamically]
            VerticalLayout {
                    spacing: 5px;

                    Image {
                        width: 80px;
                        height: 80px;
                        source: @image-url("../assets/tv-icon.svg");
                    }

                    Text {
                        text: "Placeholder";
                        font-size: 14px;
                    }
                }
            }
        }
    }
}

// Define the MoviePage component
export component MoviePage inherits Page {
    has-back-button: true;
    in-out property <string> movie_name: "Movie-Name"; // Default header
    in-out property <image> img-background;
    in-out property <image> img-poster;
    in-out property <string> extension;
    in-out property <int> stream_id;
    in-out property <SubPage> current-subpage: SubPage.MovieSite;

    in-out property <float> download_progress: 0.0;
    in-out property <bool> is_downloading: false;
    in-out property <bool> is_downloaded: false;

    callback on_movie_selected(int, string);
    callback on_movie_download(int, string);

    header: movie_name;
    extension: extension;
    stream_id: stream_id;

    // Header
    Rectangle {
        width: parent.width;
        height: parent.height;
        padding: 10px;

        // Main Content
        HorizontalLayout {
            height: 60%;
            y: 80px;
            MainContent {
                width: parent.width;
                height: parent.height;
                // height: 60%;
                img-background: img-background;
                img-poster: img-poster;
                download_progress: download_progress;
                is_downloaded: is_downloaded;
                is_downloading: is_downloading;
                // x: 0px;
                // y: 80px;
                on_movie_selected => {
                    // debug("Calling on_movie_selected from MoviePage");
                    root.on_movie_selected(stream_id, extension);
                }

                on_movie_download => {
                    root.on_movie_download(stream_id, extension);
                }
            }
        }

        // Cast Section
        HorizontalLayout {
            height: 40%;
            y: root.height * 0.6 + 80px;

            CastSection {
                width: parent.width;
                height: parent.height;
            }
        }
    }
}
