// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DemoPalette, Page, SpinBox, ComboBox, CheckBox, Label } from "common.slint";

export component SettingsPage inherits Page {
    header: @tr("Settings");

    GridLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;
        Row {
            Text {
                colspan: 4;
                text: @tr("General");
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Label { text: @tr("Account Name:"); }

            Rectangle {}

            Label { text: @tr("Expiry Date:"); }
            
        }
        Row { Rectangle {} }
    }

}
